---
- hosts: all
  tasks:
    - name: Download istio
      get_url:
        url: https://raw.githubusercontent.com/istio/istio/master/release/downloadIstioCandidate.sh
        dest: /home/vagrant/downloadIstio.sh
        mode: 0755

    - name: Install istio
      shell: "/home/vagrant/downloadIstio.sh && rm /home/vagrant/downloadIstio.sh"
      environment:
        ISTIO_VERSION: "{{ istio_version }}"
        TARGET_ARCH: x86_64

    - name: Apply istio demo profile
      shell: "/home/vagrant/istio-{{ istio_version }}/bin/istioctl install --set profile=demo -y"

    - name: Apply istio demo profile
      shell: "kubectl label namespace default istio-injection=enabled"
